name: Build Electron Desktop App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Wine (for Windows builds)
        run: sudo apt-get update && sudo apt-get install -y wine64

      - name: Build Electron App (Windows EXE)
        run: npx electron-packager . BluewaveExpress --platform=win32 --arch=x64 --icon=icon.ico --out=dist --overwrite

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BluewaveExpress-Windows
          path: dist/
